// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTheme():Promise<{[key: string]: string}>;

export function HideWindow():Promise<void>;

export function SendText(arg1:string):Promise<void>;

export function SetTTYSize(arg1:number,arg2:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function Start():Promise<void>;

export function StartTTY():Promise<void>;
