// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDarkTheme():Promise<main.Theme>;

export function GetLightTheme():Promise<main.Theme>;

export function SendText(arg1:string):Promise<void>;

export function SetTTYSize(arg1:number,arg2:number):Promise<void>;

export function Start():Promise<void>;

export function StartTTY():Promise<void>;
