// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function SendText(arg1) {
  return window['go']['main']['App']['SendText'](arg1);
}

export function SetTTYSize(arg1, arg2) {
  return window['go']['main']['App']['SetTTYSize'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function StartTTY() {
  return window['go']['main']['App']['StartTTY']();
}
